import type { Industry, IndustryData } from "@/lib/types";

// ---------------------------------------------------------------------------
// Mock data layer. Shaped exactly like the real provider will be so the UI can
// swap to live free-tier sources (SEC EDGAR, UN Comtrade, GDELT, Yahoo) later
// without changing components.
// ---------------------------------------------------------------------------

const semiconductor: IndustryData = {
  kpis: [
    { label: "Companies Tracked", value: "10", icon: "Building2", accent: "#3b82f6" },
    { label: "Suppliers & Vendors Monitored", value: "2,543", icon: "Users", accent: "#a78bfa" },
    { label: "Facilities Worldwide", value: "1,246", icon: "Factory", accent: "#22d3ee" },
    { label: "Raw Materials Tracked", value: "3,782", icon: "Boxes", accent: "#f59e0b" },
    { label: "Countries Monitored", value: "127", icon: "Globe", accent: "#34d399" },
    { label: "Policy & Regulatory Updates", value: "68", icon: "Scale", accent: "#f472b6" },
    { label: "News Impacting Markets", value: "152", icon: "Newspaper", accent: "#60a5fa" },
  ],
  companies: [
    { id: "nvidia", name: "NVIDIA", ticker: "NVDA", marketCap: "$2.31T", price: "934.89", change24h: 2.35, changeYtd: 89.45 },
    { id: "broadcom", name: "Broadcom", ticker: "AVGO", marketCap: "$1.15T", price: "245.30", change24h: 1.54, changeYtd: 38.60 },
    { id: "tsmc", name: "TSMC", ticker: "TSM", marketCap: "$846.21B", price: "162.35", change24h: 1.23, changeYtd: 34.21 },
    { id: "samsung", name: "Samsung", ticker: "005930.KS", marketCap: "$456.72B", price: "68.42", change24h: -0.45, changeYtd: 15.32 },
    { id: "asml", name: "ASML", ticker: "ASML", marketCap: "$382.59B", price: "980.45", change24h: 1.87, changeYtd: 28.74 },
    { id: "amd", name: "AMD", ticker: "AMD", marketCap: "$310.52B", price: "192.40", change24h: 2.10, changeYtd: 18.45 },
    { id: "amat", name: "Applied Materials", ticker: "AMAT", marketCap: "$185.20B", price: "228.10", change24h: 0.92, changeYtd: 21.30 },
    { id: "intel", name: "Intel", ticker: "INTC", marketCap: "$181.34B", price: "43.61", change24h: -1.02, changeYtd: -3.21 },
    { id: "arm", name: "Arm Holdings", ticker: "ARM", marketCap: "$145.03B", price: "138.20", change24h: 1.35, changeYtd: 25.10 },
    { id: "skhynix", name: "SK hynix", ticker: "000660.KS", marketCap: "$130.52B", price: "91.23", change24h: 2.15, changeYtd: 41.23 },
    { id: "lam", name: "Lam Research", ticker: "LRCX", marketCap: "$128.41B", price: "101.20", change24h: 0.74, changeYtd: 19.80 },
    { id: "qualcomm", name: "Qualcomm", ticker: "QCOM", marketCap: "$127.88B", price: "143.20", change24h: 0.78, changeYtd: 12.45 },
    { id: "kla", name: "KLA", ticker: "KLAC", marketCap: "$115.60B", price: "862.40", change24h: 0.65, changeYtd: 22.90 },
    { id: "micron", name: "Micron", ticker: "MU", marketCap: "$112.35B", price: "122.37", change24h: 1.65, changeYtd: 24.33 },
    { id: "adi", name: "Analog Devices", ticker: "ADI", marketCap: "$110.30B", price: "222.10", change24h: 0.28, changeYtd: 9.60 },
    { id: "ti", name: "Texas Instruments", ticker: "TXN", marketCap: "$96.21B", price: "171.23", change24h: 0.35, changeYtd: 8.21 },
    { id: "tel", name: "Tokyo Electron", ticker: "8035.T", marketCap: "$92.30B", price: "165.30", change24h: 1.05, changeYtd: 16.70 },
    { id: "mediatek", name: "MediaTek", ticker: "2454.TW", marketCap: "$85.40B", price: "42.10", change24h: 0.88, changeYtd: 14.20 },
    { id: "infineon", name: "Infineon", ticker: "IFX.DE", marketCap: "$69.15B", price: "34.21", change24h: -0.15, changeYtd: 6.12 },
    { id: "nxp", name: "NXP", ticker: "NXPI", marketCap: "$58.20B", price: "229.50", change24h: -0.42, changeYtd: 4.80 },
  ],
  facilities: [
    // Every company gets an HQ plus at least one manufacturing / R&D unit.
    { id: "f1", companyId: "tsmc", name: "Fab 18 (Hsinchu)", lat: 24.77, lng: 121.02, city: "Hsinchu", country: "Taiwan", type: "fab", status: "operating" },
    { id: "f2", companyId: "tsmc", name: "Arizona Fab", lat: 33.45, lng: -112.07, city: "Phoenix", country: "USA", type: "fab", status: "construction" },
    { id: "f3", companyId: "tsmc", name: "Kumamoto Fab", lat: 32.79, lng: 130.74, city: "Kumamoto", country: "Japan", type: "fab", status: "operating" },
    { id: "f4", companyId: "samsung", name: "Pyeongtaek", lat: 36.99, lng: 127.11, city: "Pyeongtaek", country: "South Korea", type: "fab", status: "operating" },
    { id: "f5", companyId: "samsung", name: "Taylor, TX", lat: 30.57, lng: -97.41, city: "Taylor", country: "USA", type: "fab", status: "construction" },
    { id: "f6", companyId: "intel", name: "Ohio Fab", lat: 40.06, lng: -82.43, city: "New Albany", country: "USA", type: "fab", status: "planned" },
    { id: "f7", companyId: "intel", name: "Leixlip Fab (Ireland)", lat: 53.36, lng: -6.49, city: "Leixlip", country: "Ireland", type: "fab", status: "operating" },
    { id: "f8", companyId: "asml", name: "Veldhoven HQ", lat: 51.42, lng: 5.4, city: "Veldhoven", country: "Netherlands", type: "hq", status: "operating" },
    { id: "f9", companyId: "skhynix", name: "Icheon Fab", lat: 37.28, lng: 127.44, city: "Icheon", country: "South Korea", type: "fab", status: "operating" },
    { id: "f10", companyId: "micron", name: "Boise R&D", lat: 43.62, lng: -116.2, city: "Boise", country: "USA", type: "rnd", status: "operating" },
    { id: "f11", companyId: "nvidia", name: "Santa Clara HQ", lat: 37.35, lng: -121.97, city: "Santa Clara", country: "USA", type: "hq", status: "operating" },
    { id: "f12", companyId: "infineon", name: "Dresden Fab", lat: 51.05, lng: 13.74, city: "Dresden", country: "Germany", type: "fab", status: "risk" },
    { id: "f13", companyId: "tsmc", name: "Dresden (ESMC)", lat: 51.06, lng: 13.72, city: "Dresden", country: "Germany", type: "fab", status: "construction" },
    { id: "f14", companyId: "samsung", name: "Xi'an Fab", lat: 34.34, lng: 108.94, city: "Xi'an", country: "China", type: "fab", status: "risk" },
    { id: "f15", companyId: "tsmc", name: "Hsinchu HQ", lat: 24.81, lng: 120.97, city: "Hsinchu", country: "Taiwan", type: "hq", status: "operating" },
    { id: "f16", companyId: "samsung", name: "Suwon HQ", lat: 37.26, lng: 127.03, city: "Suwon", country: "South Korea", type: "hq", status: "operating" },
    { id: "f17", companyId: "intel", name: "Santa Clara HQ", lat: 37.39, lng: -121.96, city: "Santa Clara", country: "USA", type: "hq", status: "operating" },
    { id: "f18", companyId: "nvidia", name: "Yokneam R&D (Israel)", lat: 32.66, lng: 35.1, city: "Yokneam", country: "Israel", type: "rnd", status: "operating" },
    { id: "f19", companyId: "broadcom", name: "Palo Alto HQ", lat: 37.38, lng: -122.14, city: "Palo Alto", country: "USA", type: "hq", status: "operating" },
    { id: "f20", companyId: "broadcom", name: "Penang Assembly & Test", lat: 5.35, lng: 100.3, city: "Penang", country: "Malaysia", type: "backend", status: "operating" },
    { id: "f21", companyId: "asml", name: "San Diego (Cymer light sources)", lat: 32.9, lng: -117.2, city: "San Diego", country: "USA", type: "fab", status: "operating" },
    { id: "f22", companyId: "amd", name: "Santa Clara HQ", lat: 37.38, lng: -121.96, city: "Santa Clara", country: "USA", type: "hq", status: "operating" },
    { id: "f23", companyId: "amd", name: "Markham R&D (Canada)", lat: 43.86, lng: -79.34, city: "Markham", country: "Canada", type: "rnd", status: "operating" },
    { id: "f24", companyId: "amat", name: "Santa Clara HQ", lat: 37.36, lng: -121.94, city: "Santa Clara", country: "USA", type: "hq", status: "operating" },
    { id: "f25", companyId: "amat", name: "Austin Manufacturing", lat: 30.21, lng: -97.75, city: "Austin", country: "USA", type: "fab", status: "operating" },
    { id: "f26", companyId: "arm", name: "Cambridge HQ (UK)", lat: 52.2, lng: 0.13, city: "Cambridge", country: "UK", type: "hq", status: "operating" },
    { id: "f27", companyId: "arm", name: "Austin Design Center", lat: 30.39, lng: -97.72, city: "Austin", country: "USA", type: "rnd", status: "operating" },
    { id: "f28", companyId: "skhynix", name: "Icheon HQ", lat: 37.27, lng: 127.43, city: "Icheon", country: "South Korea", type: "hq", status: "operating" },
    { id: "f29", companyId: "skhynix", name: "Wuxi Fab (China)", lat: 31.57, lng: 120.3, city: "Wuxi", country: "China", type: "fab", status: "risk" },
    { id: "f30", companyId: "lam", name: "Fremont HQ", lat: 37.53, lng: -121.96, city: "Fremont", country: "USA", type: "hq", status: "operating" },
    { id: "f31", companyId: "lam", name: "Tualatin Manufacturing (OR)", lat: 45.38, lng: -122.76, city: "Tualatin", country: "USA", type: "fab", status: "operating" },
    { id: "f32", companyId: "qualcomm", name: "San Diego HQ", lat: 32.9, lng: -117.19, city: "San Diego", country: "USA", type: "hq", status: "operating" },
    { id: "f33", companyId: "qualcomm", name: "Hyderabad R&D (India)", lat: 17.44, lng: 78.38, city: "Hyderabad", country: "India", type: "rnd", status: "operating" },
    { id: "f34", companyId: "kla", name: "Milpitas HQ", lat: 37.43, lng: -121.9, city: "Milpitas", country: "USA", type: "hq", status: "operating" },
    { id: "f35", companyId: "kla", name: "Migdal HaEmek Plant (Israel)", lat: 32.67, lng: 35.24, city: "Migdal HaEmek", country: "Israel", type: "fab", status: "operating" },
    { id: "f36", companyId: "micron", name: "Boise HQ", lat: 43.6, lng: -116.2, city: "Boise", country: "USA", type: "hq", status: "operating" },
    { id: "f37", companyId: "micron", name: "Hiroshima DRAM Fab", lat: 34.39, lng: 132.45, city: "Hiroshima", country: "Japan", type: "fab", status: "operating" },
    { id: "f38", companyId: "adi", name: "Wilmington HQ (MA)", lat: 42.55, lng: -71.17, city: "Wilmington", country: "USA", type: "hq", status: "operating" },
    { id: "f39", companyId: "adi", name: "Limerick Fab (Ireland)", lat: 52.66, lng: -8.63, city: "Limerick", country: "Ireland", type: "fab", status: "operating" },
    { id: "f40", companyId: "ti", name: "Dallas HQ", lat: 32.91, lng: -96.75, city: "Dallas", country: "USA", type: "hq", status: "operating" },
    { id: "f41", companyId: "ti", name: "Sherman Fab (TX)", lat: 33.64, lng: -96.61, city: "Sherman", country: "USA", type: "fab", status: "construction" },
    { id: "f42", companyId: "tel", name: "Tokyo HQ", lat: 35.65, lng: 139.76, city: "Tokyo", country: "Japan", type: "hq", status: "operating" },
    { id: "f43", companyId: "tel", name: "Miyagi Plant", lat: 38.4, lng: 140.9, city: "Miyagi", country: "Japan", type: "fab", status: "operating" },
    { id: "f44", companyId: "mediatek", name: "Hsinchu HQ", lat: 24.78, lng: 121.0, city: "Hsinchu", country: "Taiwan", type: "hq", status: "operating" },
    { id: "f45", companyId: "mediatek", name: "Singapore R&D", lat: 1.3, lng: 103.79, city: "Singapore", country: "Singapore", type: "rnd", status: "operating" },
    { id: "f46", companyId: "infineon", name: "Neubiberg HQ (Germany)", lat: 48.08, lng: 11.66, city: "Neubiberg", country: "Germany", type: "hq", status: "operating" },
    { id: "f47", companyId: "infineon", name: "Kulim Fab (Malaysia)", lat: 5.37, lng: 100.56, city: "Kulim", country: "Malaysia", type: "fab", status: "operating" },
    { id: "f48", companyId: "nxp", name: "Eindhoven HQ (Netherlands)", lat: 51.44, lng: 5.46, city: "Eindhoven", country: "Netherlands", type: "hq", status: "operating" },
    { id: "f49", companyId: "nxp", name: "Austin Fab", lat: 30.24, lng: -97.83, city: "Austin", country: "USA", type: "fab", status: "operating" },
    { id: "f50", companyId: "broadcom", name: "Fort Collins R&D (CO)", lat: 40.55, lng: -105.07, city: "Fort Collins", country: "USA", type: "rnd", status: "operating" },
    { id: "f51", companyId: "intel", name: "Haifa R&D (Israel)", lat: 32.79, lng: 34.96, city: "Haifa", country: "Israel", type: "rnd", status: "operating" },
    { id: "f52", companyId: "intel", name: "Kiryat Gat Fab 28 (Israel)", lat: 31.61, lng: 34.77, city: "Kiryat Gat", country: "Israel", type: "fab", status: "operating" },
  ],
  news: [
    { id: "n1", company: "NVIDIA", headline: "NVIDIA announces new AI chip architecture Blackwell", impact: "high", impactLabel: "Market Impact: High", ago: "2h ago", date: "2024-03-18" },
    { id: "n2", company: "TSMC", headline: "TSMC to build new fab in Germany with €10B investment", impact: "high", impactLabel: "Market Impact: High", ago: "5h ago", date: "2023-08-08" },
    { id: "n3", company: "USA", headline: "US tightens export restrictions on advanced chips to China", impact: "high", impactLabel: "Policy Impact: High", ago: "1d ago", date: "2024-12-02" },
    { id: "n4", company: "Lithium", headline: "Neon supply concerns resurface amid Eastern Europe tensions", impact: "medium", impactLabel: "Market Impact: Medium", ago: "1d ago", date: "2022-03-04" },
    { id: "n5", company: "Samsung", headline: "Samsung signs $16.5B foundry supply deal", impact: "medium", impactLabel: "Market Impact: Medium", ago: "1d ago", date: "2025-07-28" },
  ],
  sankey: {
    nodes: [
      { name: "China" }, { name: "Japan" }, { name: "USA" }, { name: "Germany" }, { name: "Ukraine" },
      { name: "Silicon" }, { name: "Rare Earths" }, { name: "Photoresist" }, { name: "Gallium" }, { name: "Neon" },
      { name: "Taiwan" }, { name: "South Korea" }, { name: "USA " }, { name: "Japan " },
    ],
    links: [
      { source: 0, target: 5, value: 18 }, { source: 0, target: 6, value: 30 }, { source: 0, target: 8, value: 28 },
      { source: 1, target: 7, value: 26 }, { source: 2, target: 5, value: 14 }, { source: 3, target: 5, value: 12 },
      { source: 4, target: 9, value: 16 },
      { source: 5, target: 10, value: 20 }, { source: 5, target: 11, value: 14 }, { source: 5, target: 12, value: 12 },
      { source: 6, target: 10, value: 12 }, { source: 6, target: 13, value: 10 },
      { source: 7, target: 10, value: 12 }, { source: 7, target: 11, value: 10 },
      { source: 8, target: 10, value: 10 }, { source: 8, target: 12, value: 8 },
      { source: 9, target: 10, value: 10 }, { source: 9, target: 11, value: 8 },
    ],
  },
  financials: [
    { company: "NVIDIA", revenue: 235, profit: 120, rnd: 8.67, capex: 3.2 },
    { company: "TSMC", revenue: 90, profit: 36, rnd: 7.23, capex: 32 },
    { company: "Samsung", revenue: 200, profit: 27, rnd: 22.1, capex: 38 },
    { company: "ASML", revenue: 30, profit: 9, rnd: 4.5, capex: 2.1 },
    { company: "Intel", revenue: 53, profit: -0.3, rnd: 16, capex: 25 },
    { company: "SK hynix", revenue: 45, profit: 8, rnd: 3.6, capex: 12 },
    { company: "Qualcomm", revenue: 38, profit: 10, rnd: 8.8, capex: 1.5 },
    { company: "Micron", revenue: 25, profit: 5, rnd: 3.1, capex: 8 },
    { company: "TI", revenue: 17, profit: 6, rnd: 1.9, capex: 5 },
    { company: "Infineon", revenue: 16, profit: 3, rnd: 2.0, capex: 3 },
  ],
  deals: [
    { date: "May 20, 2024", parties: "TSMC ↔ Bosch", type: "Manufacturing Agreement", value: "$5.0B", description: "Long-term chip supply agreement" },
    { date: "May 18, 2024", parties: "Samsung ↔ Tesla", type: "Supply Agreement", value: "$16.5B", description: "AI chip supply for Tesla vehicles" },
    { date: "May 15, 2024", parties: "SK hynix ↔ NVIDIA", type: "Memory Supply", value: "$3.2B", description: "HBM memory supply agreement" },
    { date: "May 10, 2024", parties: "ASML ↔ Intel", type: "Equipment Supply", value: "$2.1B", description: "EUV lithography systems" },
    { date: "May 08, 2024", parties: "LG Energy ↔ GM", type: "Joint Venture", value: "$2.3B", description: "Battery cell manufacturing JV" },
  ],
  suppliers: [
    { name: "Applied Materials", category: "Equipment", spend: "$15.2B", risk: "medium" },
    { name: "ASML", category: "Equipment", spend: "$12.8B", risk: "medium" },
    { name: "Tokyo Electron", category: "Equipment", spend: "$9.7B", risk: "low" },
    { name: "Shin-Etsu Chemical", category: "Materials", spend: "$7.1B", risk: "low" },
    { name: "SUMCO", category: "Materials", spend: "$6.3B", risk: "medium" },
  ],
  research: [
    { company: "NVIDIA", rndExpense: "$8.67B", rndPctRevenue: "19.8%", patents: "1,867" },
    { company: "TSMC", rndExpense: "$7.23B", rndPctRevenue: "8.6%", patents: "2,615" },
    { company: "Samsung", rndExpense: "$22.1B", rndPctRevenue: "9.6%", patents: "7,123" },
    { company: "Intel", rndExpense: "$16.0B", rndPctRevenue: "32.1%", patents: "4,193" },
    { company: "Qualcomm", rndExpense: "$6.42B", rndPctRevenue: "24.3%", patents: "2,341" },
  ],
  companyMeta: {
    nvidia: { ceo: "Jensen Huang", hq: "Santa Clara, USA", employees: "29,600", founded: "1993", description: "Designs GPUs and accelerated-computing platforms powering AI, gaming, and datacenters.", healthScore: 94, exposure: "medium", segments: [{ name: "Data Center", share: 78 }, { name: "Gaming", share: 17 }, { name: "Pro Viz / Auto", share: 5 }] },
    tsmc: { ceo: "C.C. Wei", hq: "Hsinchu, Taiwan", employees: "73,000", founded: "1987", description: "World's largest dedicated semiconductor foundry, producing advanced logic for fabless designers.", healthScore: 88, exposure: "high", segments: [{ name: "HPC", share: 46 }, { name: "Smartphone", share: 33 }, { name: "IoT / Auto", share: 21 }] },
    samsung: { ceo: "Jong-Hee Han", hq: "Suwon, South Korea", employees: "267,000", founded: "1969", description: "Integrated memory + logic maker and the second-largest foundry.", healthScore: 79, exposure: "high", segments: [{ name: "Memory", share: 55 }, { name: "Foundry / LSI", share: 30 }, { name: "Other", share: 15 }] },
    asml: { ceo: "Christophe Fouquet", hq: "Veldhoven, Netherlands", employees: "42,000", founded: "1984", description: "Sole supplier of EUV lithography systems — a critical chokepoint in leading-edge chipmaking.", healthScore: 90, exposure: "medium", segments: [{ name: "EUV Systems", share: 48 }, { name: "DUV Systems", share: 34 }, { name: "Service", share: 18 }] },
    intel: { ceo: "Lip-Bu Tan", hq: "Santa Clara, USA", employees: "108,900", founded: "1968", description: "Integrated device manufacturer investing heavily in a foundry turnaround.", healthScore: 58, exposure: "high", segments: [{ name: "Client", share: 51 }, { name: "Data Center", share: 30 }, { name: "Foundry / Other", share: 19 }] },
    skhynix: { ceo: "Kwak Noh-Jung", hq: "Icheon, South Korea", employees: "31,000", founded: "1983", description: "Memory maker and leading supplier of HBM for AI accelerators.", healthScore: 82, exposure: "high", segments: [{ name: "DRAM / HBM", share: 71 }, { name: "NAND", share: 29 }] },
    qualcomm: { ceo: "Cristiano Amon", hq: "San Diego, USA", employees: "50,000", founded: "1985", description: "Fabless leader in mobile SoCs and wireless connectivity IP.", healthScore: 76, exposure: "medium", segments: [{ name: "Handsets", share: 64 }, { name: "IoT", share: 22 }, { name: "Automotive", share: 14 }] },
    micron: { ceo: "Sanjay Mehrotra", hq: "Boise, USA", employees: "48,000", founded: "1978", description: "US-based DRAM and NAND memory manufacturer.", healthScore: 74, exposure: "high", segments: [{ name: "DRAM", share: 73 }, { name: "NAND", share: 27 }] },
    ti: { ceo: "Haviv Ilan", hq: "Dallas, USA", employees: "34,000", founded: "1930", description: "Broad-line analog and embedded-processing supplier with in-house fabs.", healthScore: 80, exposure: "low", segments: [{ name: "Analog", share: 74 }, { name: "Embedded", share: 18 }, { name: "Other", share: 8 }] },
    infineon: { ceo: "Jochen Hanebeck", hq: "Neubiberg, Germany", employees: "58,000", founded: "1999", description: "Power semiconductors and automotive/industrial microcontrollers.", healthScore: 77, exposure: "medium", segments: [{ name: "Automotive", share: 48 }, { name: "Power & Sensor", share: 30 }, { name: "Connected / Secure", share: 22 }] },
  },
};

const ai: IndustryData = {
  kpis: [
    { label: "Companies Tracked", value: "10", icon: "Building2", accent: "#3b82f6" },
    { label: "Suppliers & Vendors Monitored", value: "1,884", icon: "Users", accent: "#a78bfa" },
    { label: "Facilities Worldwide", value: "612", icon: "Factory", accent: "#22d3ee" },
    { label: "Raw Materials Tracked", value: "1,204", icon: "Boxes", accent: "#f59e0b" },
    { label: "Countries Monitored", value: "84", icon: "Globe", accent: "#34d399" },
    { label: "Policy & Regulatory Updates", value: "91", icon: "Scale", accent: "#f472b6" },
    { label: "News Impacting Markets", value: "203", icon: "Newspaper", accent: "#60a5fa" },
  ],
  companies: [
    { id: "microsoft", name: "Microsoft", ticker: "MSFT", marketCap: "$3.11T", price: "418.32", change24h: 0.92, changeYtd: 22.14 },
    { id: "alphabet", name: "Alphabet", ticker: "GOOGL", marketCap: "$2.10T", price: "168.22", change24h: 1.11, changeYtd: 30.02 },
    { id: "amazon", name: "Amazon", ticker: "AMZN", marketCap: "$1.92T", price: "184.70", change24h: 0.54, changeYtd: 20.31 },
    { id: "meta", name: "Meta", ticker: "META", marketCap: "$1.28T", price: "502.30", change24h: 1.42, changeYtd: 42.18 },
    { id: "openai", name: "OpenAI", ticker: "Private", marketCap: "$300.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "alibaba", name: "Alibaba", ticker: "BABA", marketCap: "$205.0B", price: "85.20", change24h: 0.85, changeYtd: 11.40 },
    { id: "palantir", name: "Palantir", ticker: "PLTR", marketCap: "$180.0B", price: "76.40", change24h: 1.90, changeYtd: 44.60 },
    { id: "anthropic", name: "Anthropic", ticker: "Private", marketCap: "$61.5B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "databricks", name: "Databricks", ticker: "Private", marketCap: "$62.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "xai", name: "xAI", ticker: "Private", marketCap: "$50.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "perplexity", name: "Perplexity", ticker: "Private", marketCap: "$18.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "scaleai", name: "Scale AI", ticker: "Private", marketCap: "$13.8B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "midjourney", name: "Midjourney", ticker: "Private", marketCap: "$10.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "cerebras", name: "Cerebras", ticker: "Private", marketCap: "$8.1B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "mistral", name: "Mistral AI", ticker: "Private", marketCap: "$6.2B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "cohere", name: "Cohere", ticker: "Private", marketCap: "$5.5B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "abridge", name: "Abridge", ticker: "Private", marketCap: "$5.3B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "huggingface", name: "Hugging Face", ticker: "Private", marketCap: "$4.5B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "runway", name: "Runway", ticker: "Private", marketCap: "$4.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "deepseek", name: "DeepSeek", ticker: "Private", marketCap: "$3.4B", price: "—", change24h: 0, changeYtd: 0 },
  ],
  facilities: [
    // Every company gets an HQ plus at least one datacenter / R&D unit.
    { id: "a1", companyId: "microsoft", name: "Azure US-East DC", lat: 37.43, lng: -78.65, city: "Boydton", country: "USA", type: "backend", status: "operating" },
    { id: "a2", companyId: "amazon", name: "AWS Oregon", lat: 45.87, lng: -119.69, city: "Boardman", country: "USA", type: "backend", status: "operating" },
    { id: "a3", companyId: "alphabet", name: "Google DC Finland", lat: 60.56, lng: 27.19, city: "Hamina", country: "Finland", type: "backend", status: "operating" },
    { id: "a4", companyId: "meta", name: "Meta DC Ireland", lat: 53.35, lng: -6.26, city: "Dublin", country: "Ireland", type: "backend", status: "operating" },
    { id: "a5", companyId: "xai", name: "xAI Colossus (Memphis)", lat: 35.05, lng: -90.05, city: "Memphis", country: "USA", type: "backend", status: "operating" },
    { id: "a6", companyId: "microsoft", name: "Azure Middle East", lat: 24.47, lng: 54.37, city: "Abu Dhabi", country: "UAE", type: "backend", status: "planned" },
    { id: "a7", companyId: "anthropic", name: "San Francisco HQ", lat: 37.79, lng: -122.4, city: "San Francisco", country: "USA", type: "hq", status: "operating" },
    { id: "a8", companyId: "openai", name: "Stargate (Abilene, TX)", lat: 32.45, lng: -99.73, city: "Abilene", country: "USA", type: "backend", status: "construction" },
    { id: "a9", companyId: "microsoft", name: "Azure Singapore", lat: 1.35, lng: 103.82, city: "Singapore", country: "Singapore", type: "backend", status: "risk" },
    { id: "a10", companyId: "alphabet", name: "Google DC Taiwan", lat: 23.5, lng: 120.4, city: "Changhua", country: "Taiwan", type: "backend", status: "risk" },
    { id: "a11", companyId: "microsoft", name: "Redmond HQ", lat: 47.64, lng: -122.13, city: "Redmond", country: "USA", type: "hq", status: "operating" },
    { id: "a12", companyId: "alphabet", name: "Mountain View HQ", lat: 37.42, lng: -122.08, city: "Mountain View", country: "USA", type: "hq", status: "operating" },
    { id: "a13", companyId: "amazon", name: "Seattle HQ", lat: 47.62, lng: -122.34, city: "Seattle", country: "USA", type: "hq", status: "operating" },
    { id: "a14", companyId: "meta", name: "Menlo Park HQ", lat: 37.48, lng: -122.15, city: "Menlo Park", country: "USA", type: "hq", status: "operating" },
    { id: "a15", companyId: "openai", name: "San Francisco HQ", lat: 37.76, lng: -122.41, city: "San Francisco", country: "USA", type: "hq", status: "operating" },
    { id: "a16", companyId: "alibaba", name: "Hangzhou HQ", lat: 30.2, lng: 120.19, city: "Hangzhou", country: "China", type: "hq", status: "operating" },
    { id: "a17", companyId: "alibaba", name: "Alibaba Cloud DC (Zhangbei)", lat: 41.15, lng: 114.7, city: "Zhangbei", country: "China", type: "backend", status: "operating" },
    { id: "a18", companyId: "palantir", name: "Denver HQ", lat: 39.75, lng: -104.99, city: "Denver", country: "USA", type: "hq", status: "operating" },
    { id: "a19", companyId: "palantir", name: "London R&D", lat: 51.51, lng: -0.13, city: "London", country: "UK", type: "rnd", status: "operating" },
    { id: "a20", companyId: "anthropic", name: "London Office (R&D)", lat: 51.52, lng: -0.1, city: "London", country: "UK", type: "rnd", status: "operating" },
    { id: "a21", companyId: "databricks", name: "San Francisco HQ", lat: 37.79, lng: -122.39, city: "San Francisco", country: "USA", type: "hq", status: "operating" },
    { id: "a22", companyId: "databricks", name: "Amsterdam R&D", lat: 52.34, lng: 4.89, city: "Amsterdam", country: "Netherlands", type: "rnd", status: "operating" },
    { id: "a23", companyId: "xai", name: "Palo Alto HQ", lat: 37.44, lng: -122.16, city: "Palo Alto", country: "USA", type: "hq", status: "operating" },
    { id: "a24", companyId: "perplexity", name: "San Francisco HQ", lat: 37.79, lng: -122.4, city: "San Francisco", country: "USA", type: "hq", status: "operating" },
    { id: "a25", companyId: "perplexity", name: "New York Office (R&D)", lat: 40.74, lng: -74.0, city: "New York", country: "USA", type: "rnd", status: "operating" },
    { id: "a26", companyId: "scaleai", name: "San Francisco HQ", lat: 37.77, lng: -122.4, city: "San Francisco", country: "USA", type: "hq", status: "operating" },
    { id: "a27", companyId: "scaleai", name: "St. Louis Office (Ops)", lat: 38.63, lng: -90.2, city: "St. Louis", country: "USA", type: "rnd", status: "operating" },
    { id: "a28", companyId: "midjourney", name: "San Francisco HQ", lat: 37.77, lng: -122.42, city: "San Francisco", country: "USA", type: "hq", status: "operating" },
    { id: "a29", companyId: "midjourney", name: "London Office (R&D)", lat: 51.51, lng: -0.12, city: "London", country: "UK", type: "rnd", status: "operating" },
    { id: "a30", companyId: "cerebras", name: "Sunnyvale HQ", lat: 37.39, lng: -122.03, city: "Sunnyvale", country: "USA", type: "hq", status: "operating" },
    { id: "a31", companyId: "cerebras", name: "Dallas Inference DC", lat: 32.78, lng: -96.8, city: "Dallas", country: "USA", type: "backend", status: "operating" },
    { id: "a32", companyId: "mistral", name: "Paris HQ", lat: 48.87, lng: 2.35, city: "Paris", country: "France", type: "hq", status: "operating" },
    { id: "a33", companyId: "mistral", name: "London Office (R&D)", lat: 51.51, lng: -0.12, city: "London", country: "UK", type: "rnd", status: "operating" },
    { id: "a34", companyId: "cohere", name: "Toronto HQ", lat: 43.65, lng: -79.38, city: "Toronto", country: "Canada", type: "hq", status: "operating" },
    { id: "a35", companyId: "cohere", name: "San Francisco Office (R&D)", lat: 37.79, lng: -122.4, city: "San Francisco", country: "USA", type: "rnd", status: "operating" },
    { id: "a36", companyId: "abridge", name: "Pittsburgh HQ", lat: 40.44, lng: -79.99, city: "Pittsburgh", country: "USA", type: "hq", status: "operating" },
    { id: "a37", companyId: "abridge", name: "San Francisco Office (R&D)", lat: 37.78, lng: -122.4, city: "San Francisco", country: "USA", type: "rnd", status: "operating" },
    { id: "a38", companyId: "huggingface", name: "New York HQ", lat: 40.73, lng: -73.99, city: "New York", country: "USA", type: "hq", status: "operating" },
    { id: "a39", companyId: "huggingface", name: "Paris R&D", lat: 48.86, lng: 2.35, city: "Paris", country: "France", type: "rnd", status: "operating" },
    { id: "a40", companyId: "runway", name: "New York HQ", lat: 40.72, lng: -74.0, city: "New York", country: "USA", type: "hq", status: "operating" },
    { id: "a41", companyId: "runway", name: "London Office (R&D)", lat: 51.51, lng: -0.09, city: "London", country: "UK", type: "rnd", status: "operating" },
    { id: "a42", companyId: "deepseek", name: "Hangzhou HQ", lat: 30.27, lng: 120.16, city: "Hangzhou", country: "China", type: "hq", status: "operating" },
    { id: "a43", companyId: "deepseek", name: "Beijing R&D", lat: 39.98, lng: 116.31, city: "Beijing", country: "China", type: "rnd", status: "operating" },
  ],
  news: [
    { id: "an1", company: "OpenAI", headline: "OpenAI unveils next-gen model with expanded context", impact: "high", impactLabel: "Market Impact: High", ago: "3h ago", date: "2025-04-14" },
    { id: "an2", company: "Microsoft", headline: "Microsoft commits $80B to AI datacenter buildout", impact: "high", impactLabel: "Market Impact: High", ago: "6h ago", date: "2025-01-03" },
    { id: "an3", company: "USA", headline: "New AI compute export controls proposed", impact: "high", impactLabel: "Policy Impact: High", ago: "1d ago", date: "2025-01-13" },
    { id: "an4", company: "NVIDIA", headline: "HBM supply tightness expected through 2025", impact: "medium", impactLabel: "Market Impact: Medium", ago: "1d ago", date: "2024-05-21" },
    { id: "an5", company: "CoreWeave", headline: "CoreWeave secures $7.5B debt for GPU expansion", impact: "medium", impactLabel: "Market Impact: Medium", ago: "2d ago", date: "2024-05-17" },
  ],
  sankey: {
    nodes: [
      { name: "Taiwan" }, { name: "South Korea" }, { name: "USA" }, { name: "Japan" },
      { name: "GPUs" }, { name: "HBM Memory" }, { name: "CoWoS Packaging" }, { name: "AI Servers" },
      { name: "USA " }, { name: "China" }, { name: "Europe" }, { name: "Middle East" },
    ],
    links: [
      { source: 0, target: 4, value: 26 }, { source: 0, target: 6, value: 18 }, { source: 1, target: 5, value: 20 },
      { source: 2, target: 4, value: 14 }, { source: 3, target: 5, value: 6 }, { source: 3, target: 6, value: 6 },
      { source: 4, target: 7, value: 26 }, { source: 4, target: 9, value: 6 }, { source: 5, target: 7, value: 20 },
      { source: 6, target: 7, value: 18 },
      { source: 7, target: 8, value: 34 }, { source: 7, target: 10, value: 14 }, { source: 7, target: 11, value: 12 },
    ],
  },
  financials: [
    { company: "Microsoft", revenue: 245, profit: 88, rnd: 29, capex: 55 },
    { company: "NVIDIA", revenue: 235, profit: 120, rnd: 8.67, capex: 3.2 },
    { company: "Alphabet", revenue: 328, profit: 74, rnd: 45, capex: 48 },
    { company: "Amazon", revenue: 620, profit: 37, rnd: 86, capex: 75 },
    { company: "Meta", revenue: 156, profit: 55, rnd: 38, capex: 37 },
    { company: "AMD", revenue: 25, profit: 4, rnd: 6.1, capex: 0.7 },
    { company: "Oracle", revenue: 53, profit: 10, rnd: 8.9, capex: 7 },
  ],
  deals: [
    { date: "May 22, 2024", parties: "Microsoft ↔ OpenAI", type: "Partnership", value: "$10.0B", description: "Multi-year Azure compute + investment" },
    { date: "May 19, 2024", parties: "Amazon ↔ Anthropic", type: "Investment", value: "$4.0B", description: "Strategic AI investment + Trainium" },
    { date: "May 14, 2024", parties: "CoreWeave ↔ NVIDIA", type: "Supply Agreement", value: "$3.5B", description: "GPU capacity commitment" },
    { date: "May 09, 2024", parties: "Oracle ↔ xAI", type: "Cloud Agreement", value: "$2.0B", description: "Grok training cluster" },
    { date: "May 05, 2024", parties: "Meta ↔ Scale AI", type: "Investment", value: "$1.5B", description: "Data labeling partnership" },
  ],
  suppliers: [
    { name: "NVIDIA", category: "Accelerators", spend: "$28.4B", risk: "high" },
    { name: "TSMC", category: "Foundry", spend: "$14.2B", risk: "medium" },
    { name: "SK hynix", category: "HBM Memory", spend: "$9.1B", risk: "medium" },
    { name: "Dell", category: "Systems", spend: "$6.7B", risk: "low" },
    { name: "Vertiv", category: "Cooling/Power", spend: "$4.3B", risk: "low" },
  ],
  research: [
    { company: "Alphabet", rndExpense: "$45.4B", rndPctRevenue: "13.8%", patents: "9,842" },
    { company: "Microsoft", rndExpense: "$29.5B", rndPctRevenue: "12.0%", patents: "8,912" },
    { company: "Meta", rndExpense: "$38.4B", rndPctRevenue: "24.6%", patents: "3,204" },
    { company: "NVIDIA", rndExpense: "$8.67B", rndPctRevenue: "19.8%", patents: "1,867" },
    { company: "AMD", rndExpense: "$6.1B", rndPctRevenue: "24.4%", patents: "2,410" },
  ],
};

const battery: IndustryData = {
  kpis: [
    { label: "Companies Tracked", value: "10", icon: "Building2", accent: "#3b82f6" },
    { label: "Suppliers & Vendors Monitored", value: "1,320", icon: "Users", accent: "#a78bfa" },
    { label: "Facilities Worldwide", value: "884", icon: "Factory", accent: "#22d3ee" },
    { label: "Raw Materials Tracked", value: "2,140", icon: "Boxes", accent: "#f59e0b" },
    { label: "Countries Monitored", value: "96", icon: "Globe", accent: "#34d399" },
    { label: "Policy & Regulatory Updates", value: "77", icon: "Scale", accent: "#f472b6" },
    { label: "News Impacting Markets", value: "118", icon: "Newspaper", accent: "#60a5fa" },
  ],
  companies: [
    { id: "catl", name: "CATL", ticker: "300750.SZ", marketCap: "$130.4B", price: "25.60", change24h: 1.02, changeYtd: 14.32 },
    { id: "byd", name: "BYD", ticker: "1211.HK", marketCap: "$92.1B", price: "31.20", change24h: -0.62, changeYtd: 9.41 },
    { id: "tesla", name: "Tesla", ticker: "TSLA", marketCap: "$798.2B", price: "251.10", change24h: 2.14, changeYtd: -3.22 },
    { id: "lges", name: "LG Energy", ticker: "373220.KS", marketCap: "$68.0B", price: "290.00", change24h: 0.51, changeYtd: 6.10 },
    { id: "panasonic", name: "Panasonic", ticker: "6752.T", marketCap: "$28.5B", price: "12.40", change24h: -0.31, changeYtd: 3.20 },
    { id: "samsungsdi", name: "Samsung SDI", ticker: "006400.KS", marketCap: "$22.0B", price: "230.00", change24h: 0.72, changeYtd: 5.90 },
    { id: "skon", name: "SK On", ticker: "Private", marketCap: "$20.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "calb", name: "CALB", ticker: "3931.HK", marketCap: "$8.4B", price: "6.10", change24h: -1.02, changeYtd: -2.10 },
    { id: "eve", name: "EVE Energy", ticker: "300014.SZ", marketCap: "$11.2B", price: "5.80", change24h: 0.41, changeYtd: 4.30 },
    { id: "gotion", name: "Gotion", ticker: "002074.SZ", marketCap: "$6.1B", price: "3.20", change24h: -0.15, changeYtd: 1.10 },
    { id: "toshiba", name: "Toshiba", ticker: "Private", marketCap: "$14.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "clarios", name: "Clarios", ticker: "Private", marketCap: "$13.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "svolt", name: "SVOLT", ticker: "Private", marketCap: "$10.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "aesc", name: "AESC", ticker: "Private", marketCap: "$9.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "sunwoda", name: "Sunwoda", ticker: "300207.SZ", marketCap: "$8.5B", price: "3.90", change24h: 0.62, changeYtd: 7.80 },
    { id: "lishen", name: "Tianjin Lishen", ticker: "Private", marketCap: "$7.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "northvolt", name: "Northvolt", ticker: "Private", marketCap: "$6.5B", price: "—", change24h: 0, changeYtd: -35.2 },
    { id: "exide", name: "Exide Industries", ticker: "EXIDEIND.NS", marketCap: "$4.1B", price: "4.80", change24h: 0.35, changeYtd: 12.10 },
    { id: "quantumscape", name: "QuantumScape", ticker: "QS", marketCap: "$3.4B", price: "6.20", change24h: 1.80, changeYtd: -8.40 },
    { id: "gsyuasa", name: "GS Yuasa", ticker: "6674.T", marketCap: "$2.8B", price: "18.60", change24h: -0.22, changeYtd: 5.30 },
  ],
  facilities: [
    // Every company gets an HQ plus at least one plant / refinery / R&D unit.
    { id: "b1", companyId: "catl", name: "Ningde Gigafactory", lat: 26.66, lng: 119.55, city: "Ningde", country: "China", type: "fab", status: "operating" },
    { id: "b2", companyId: "catl", name: "Germany Plant (Arnstadt)", lat: 50.84, lng: 10.95, city: "Arnstadt", country: "Germany", type: "fab", status: "operating" },
    { id: "b3", companyId: "byd", name: "Shenzhen HQ", lat: 22.65, lng: 114.05, city: "Shenzhen", country: "China", type: "hq", status: "operating" },
    { id: "b4", companyId: "tesla", name: "Nevada Gigafactory", lat: 39.54, lng: -119.44, city: "Sparks", country: "USA", type: "fab", status: "operating" },
    { id: "b5", companyId: "tesla", name: "Berlin Gigafactory", lat: 52.4, lng: 13.79, city: "Grünheide", country: "Germany", type: "fab", status: "operating" },
    { id: "b6", companyId: "lges", name: "Ohio JV (Ultium)", lat: 41.16, lng: -80.58, city: "Warren", country: "USA", type: "fab", status: "construction" },
    { id: "b7", companyId: "panasonic", name: "Kansas Plant (De Soto)", lat: 39.11, lng: -95.68, city: "De Soto", country: "USA", type: "fab", status: "construction" },
    { id: "b8", companyId: "catl", name: "Lithium Refinery (Yichun)", lat: 27.81, lng: 114.42, city: "Yichun", country: "China", type: "refinery", status: "operating" },
    { id: "b9", companyId: "samsungsdi", name: "Cheonan Plant", lat: 36.81, lng: 127.11, city: "Cheonan", country: "South Korea", type: "fab", status: "operating" },
    { id: "b10", companyId: "catl", name: "DR Congo Sourcing", lat: -10.72, lng: 25.5, city: "Kolwezi", country: "DR Congo", type: "refinery", status: "risk" },
    { id: "b11", companyId: "catl", name: "Ningde HQ", lat: 26.67, lng: 119.52, city: "Ningde", country: "China", type: "hq", status: "operating" },
    { id: "b12", companyId: "byd", name: "Xi'an Battery Plant", lat: 34.27, lng: 108.95, city: "Xi'an", country: "China", type: "fab", status: "operating" },
    { id: "b13", companyId: "tesla", name: "Austin HQ (Giga Texas)", lat: 30.22, lng: -97.62, city: "Austin", country: "USA", type: "hq", status: "operating" },
    { id: "b14", companyId: "tesla", name: "Shanghai Gigafactory", lat: 31.09, lng: 121.79, city: "Shanghai", country: "China", type: "fab", status: "operating" },
    { id: "b15", companyId: "lges", name: "Seoul HQ", lat: 37.53, lng: 126.92, city: "Seoul", country: "South Korea", type: "hq", status: "operating" },
    { id: "b16", companyId: "lges", name: "Wroclaw Plant (Poland)", lat: 51.09, lng: 16.96, city: "Wroclaw", country: "Poland", type: "fab", status: "operating" },
    { id: "b17", companyId: "panasonic", name: "Osaka HQ (Kadoma)", lat: 34.73, lng: 135.63, city: "Osaka", country: "Japan", type: "hq", status: "operating" },
    { id: "b18", companyId: "samsungsdi", name: "Yongin HQ", lat: 37.22, lng: 127.18, city: "Yongin", country: "South Korea", type: "hq", status: "operating" },
    { id: "b19", companyId: "samsungsdi", name: "Göd Plant (Hungary)", lat: 47.68, lng: 19.13, city: "Göd", country: "Hungary", type: "fab", status: "operating" },
    { id: "b20", companyId: "skon", name: "Seoul HQ", lat: 37.56, lng: 126.98, city: "Seoul", country: "South Korea", type: "hq", status: "operating" },
    { id: "b21", companyId: "skon", name: "Georgia Plant (US)", lat: 34.04, lng: -83.86, city: "Commerce", country: "USA", type: "fab", status: "operating" },
    { id: "b22", companyId: "calb", name: "Changzhou HQ", lat: 31.78, lng: 119.97, city: "Changzhou", country: "China", type: "hq", status: "operating" },
    { id: "b23", companyId: "calb", name: "Xiamen Plant", lat: 24.63, lng: 118.05, city: "Xiamen", country: "China", type: "fab", status: "operating" },
    { id: "b24", companyId: "eve", name: "Huizhou HQ", lat: 23.09, lng: 114.41, city: "Huizhou", country: "China", type: "hq", status: "operating" },
    { id: "b25", companyId: "eve", name: "Jingmen Gigafactory", lat: 30.98, lng: 112.19, city: "Jingmen", country: "China", type: "fab", status: "operating" },
    { id: "b26", companyId: "gotion", name: "Hefei HQ", lat: 31.83, lng: 117.25, city: "Hefei", country: "China", type: "hq", status: "operating" },
    { id: "b27", companyId: "gotion", name: "Göttingen Plant (Germany)", lat: 51.54, lng: 9.93, city: "Göttingen", country: "Germany", type: "fab", status: "construction" },
    { id: "b28", companyId: "toshiba", name: "Tokyo HQ", lat: 35.67, lng: 139.75, city: "Tokyo", country: "Japan", type: "hq", status: "operating" },
    { id: "b29", companyId: "toshiba", name: "Kashiwazaki SCiB Plant", lat: 37.37, lng: 138.56, city: "Kashiwazaki", country: "Japan", type: "fab", status: "operating" },
    { id: "b30", companyId: "clarios", name: "Milwaukee HQ (Glendale)", lat: 43.13, lng: -87.93, city: "Milwaukee", country: "USA", type: "hq", status: "operating" },
    { id: "b31", companyId: "clarios", name: "Hannover Plant (Germany)", lat: 52.37, lng: 9.73, city: "Hannover", country: "Germany", type: "fab", status: "operating" },
    { id: "b32", companyId: "svolt", name: "Changzhou HQ", lat: 31.72, lng: 119.95, city: "Changzhou", country: "China", type: "hq", status: "operating" },
    { id: "b33", companyId: "svolt", name: "Thailand Plant (Chonburi)", lat: 13.31, lng: 100.92, city: "Chonburi", country: "Thailand", type: "fab", status: "operating" },
    { id: "b34", companyId: "aesc", name: "Yokohama HQ", lat: 35.47, lng: 139.62, city: "Yokohama", country: "Japan", type: "hq", status: "operating" },
    { id: "b35", companyId: "aesc", name: "Sunderland Plant (UK)", lat: 54.92, lng: -1.46, city: "Sunderland", country: "UK", type: "fab", status: "operating" },
    { id: "b36", companyId: "sunwoda", name: "Shenzhen HQ", lat: 22.72, lng: 113.93, city: "Shenzhen", country: "China", type: "hq", status: "operating" },
    { id: "b37", companyId: "sunwoda", name: "Nanjing Plant", lat: 31.95, lng: 118.84, city: "Nanjing", country: "China", type: "fab", status: "operating" },
    { id: "b38", companyId: "lishen", name: "Tianjin HQ", lat: 39.12, lng: 117.35, city: "Tianjin", country: "China", type: "hq", status: "operating" },
    { id: "b39", companyId: "lishen", name: "Suzhou Plant", lat: 31.3, lng: 120.62, city: "Suzhou", country: "China", type: "fab", status: "operating" },
    { id: "b40", companyId: "northvolt", name: "Stockholm HQ", lat: 59.33, lng: 18.07, city: "Stockholm", country: "Sweden", type: "hq", status: "risk" },
    { id: "b41", companyId: "northvolt", name: "Northvolt Ett (Skellefteå)", lat: 64.75, lng: 20.95, city: "Skellefteå", country: "Sweden", type: "fab", status: "risk" },
    { id: "b42", companyId: "exide", name: "Kolkata HQ (India)", lat: 22.55, lng: 88.35, city: "Kolkata", country: "India", type: "hq", status: "operating" },
    { id: "b43", companyId: "exide", name: "Haldia Plant", lat: 22.06, lng: 88.07, city: "Haldia", country: "India", type: "fab", status: "operating" },
    { id: "b44", companyId: "quantumscape", name: "San Jose HQ", lat: 37.39, lng: -121.94, city: "San Jose", country: "USA", type: "hq", status: "operating" },
    { id: "b45", companyId: "quantumscape", name: "PowerCo JV Line (Salzgitter)", lat: 52.15, lng: 10.33, city: "Salzgitter", country: "Germany", type: "fab", status: "planned" },
    { id: "b46", companyId: "gsyuasa", name: "Kyoto HQ", lat: 34.95, lng: 135.76, city: "Kyoto", country: "Japan", type: "hq", status: "operating" },
    { id: "b47", companyId: "gsyuasa", name: "Miskolc Plant (Hungary)", lat: 48.1, lng: 20.78, city: "Miskolc", country: "Hungary", type: "fab", status: "operating" },
  ],
  news: [
    { id: "bn1", company: "CATL", headline: "CATL unveils sodium-ion battery for mass production", impact: "high", impactLabel: "Market Impact: High", ago: "4h ago", date: "2025-04-21" },
    { id: "bn2", company: "Lithium", headline: "Lithium prices drop 15% amid supply glut concerns", impact: "medium", impactLabel: "Market Impact: Medium", ago: "8h ago", date: "2024-08-15" },
    { id: "bn3", company: "EU", headline: "EU Critical Raw Materials Act enters new phase", impact: "high", impactLabel: "Policy Impact: High", ago: "1d ago", date: "2024-05-23" },
    { id: "bn4", company: "DR Congo", headline: "Cobalt supply disruption risk rises in DRC", impact: "high", impactLabel: "Market Impact: High", ago: "1d ago", date: "2025-02-24" },
    { id: "bn5", company: "LG Energy", headline: "LG Energy ↔ GM expand Ultium JV capacity", impact: "medium", impactLabel: "Market Impact: Medium", ago: "2d ago", date: "2022-01-25" },
  ],
  sankey: {
    nodes: [
      { name: "Australia" }, { name: "DR Congo" }, { name: "Chile" }, { name: "China" }, { name: "Indonesia" },
      { name: "Lithium" }, { name: "Cobalt" }, { name: "Nickel" }, { name: "Graphite" },
      { name: "China " }, { name: "South Korea" }, { name: "USA" }, { name: "Europe" },
    ],
    links: [
      { source: 0, target: 5, value: 24 }, { source: 2, target: 5, value: 16 }, { source: 1, target: 6, value: 22 },
      { source: 4, target: 7, value: 26 }, { source: 3, target: 8, value: 20 }, { source: 0, target: 7, value: 8 },
      { source: 5, target: 9, value: 20 }, { source: 5, target: 10, value: 10 }, { source: 5, target: 11, value: 8 },
      { source: 6, target: 9, value: 16 }, { source: 6, target: 10, value: 8 },
      { source: 7, target: 9, value: 16 }, { source: 7, target: 12, value: 8 },
      { source: 8, target: 9, value: 12 }, { source: 8, target: 11, value: 6 },
    ],
  },
  financials: [
    { company: "Tesla", revenue: 97, profit: 15, rnd: 4.0, capex: 9 },
    { company: "CATL", revenue: 56, profit: 6, rnd: 2.5, capex: 8 },
    { company: "BYD", revenue: 84, profit: 4.5, rnd: 3.9, capex: 11 },
    { company: "LG Energy", revenue: 24, profit: 1.5, rnd: 0.9, capex: 6 },
    { company: "Panasonic", revenue: 63, profit: 3, rnd: 2.1, capex: 4 },
    { company: "Samsung SDI", revenue: 18, profit: 1.2, rnd: 0.8, capex: 3 },
  ],
  deals: [
    { date: "May 21, 2024", parties: "LG Energy ↔ GM", type: "Joint Venture", value: "$2.3B", description: "Ultium cell manufacturing JV" },
    { date: "May 17, 2024", parties: "CATL ↔ Ford", type: "Licensing", value: "$3.5B", description: "LFP battery tech licensing" },
    { date: "May 12, 2024", parties: "Tesla ↔ Panasonic", type: "Supply Agreement", value: "$4.1B", description: "4680 cell supply" },
    { date: "May 07, 2024", parties: "BYD ↔ Toyota", type: "Partnership", value: "$1.8B", description: "EV platform co-development" },
    { date: "May 03, 2024", parties: "SK On ↔ Hyundai", type: "Joint Venture", value: "$2.0B", description: "US cell plant JV" },
  ],
  suppliers: [
    { name: "Ganfeng Lithium", category: "Lithium", spend: "$8.9B", risk: "high" },
    { name: "Glencore", category: "Cobalt/Nickel", spend: "$7.2B", risk: "high" },
    { name: "Albemarle", category: "Lithium", spend: "$5.4B", risk: "medium" },
    { name: "Umicore", category: "Cathode", spend: "$4.1B", risk: "medium" },
    { name: "POSCO Future M", category: "Anode/Cathode", spend: "$3.6B", risk: "low" },
  ],
  research: [
    { company: "CATL", rndExpense: "$2.5B", rndPctRevenue: "4.5%", patents: "6,120" },
    { company: "BYD", rndExpense: "$3.9B", rndPctRevenue: "4.6%", patents: "8,410" },
    { company: "Tesla", rndExpense: "$4.0B", rndPctRevenue: "4.1%", patents: "1,940" },
    { company: "LG Energy", rndExpense: "$0.9B", rndPctRevenue: "3.8%", patents: "2,780" },
    { company: "Samsung SDI", rndExpense: "$0.8B", rndPctRevenue: "4.4%", patents: "3,010" },
  ],
};

export const DATA: Record<Industry, IndustryData> = { semiconductor, ai, battery };

export function getIndustryData(industry: Industry): IndustryData {
  return DATA[industry];
}
