import type { Industry, IndustryData } from "@/lib/types";

// ---------------------------------------------------------------------------
// Mock data layer. Shaped exactly like the real provider will be so the UI can
// swap to live free-tier sources (SEC EDGAR, UN Comtrade, GDELT, Yahoo) later
// without changing components.
// ---------------------------------------------------------------------------

const semiconductor: IndustryData = {
  kpis: [
    { label: "Companies Tracked", value: "10", icon: "Building2", accent: "#3b82f6" },
    { label: "Suppliers & Vendors Monitored", value: "2,543", icon: "Users", accent: "#a78bfa" },
    { label: "Facilities Worldwide", value: "1,246", icon: "Factory", accent: "#22d3ee" },
    { label: "Raw Materials Tracked", value: "3,782", icon: "Boxes", accent: "#f59e0b" },
    { label: "Countries Monitored", value: "127", icon: "Globe", accent: "#34d399" },
    { label: "Policy & Regulatory Updates", value: "68", icon: "Scale", accent: "#f472b6" },
    { label: "News Impacting Markets", value: "152", icon: "Newspaper", accent: "#60a5fa" },
  ],
  companies: [
    { id: "nvidia", name: "NVIDIA", ticker: "NVDA", marketCap: "$2.31T", price: "934.89", change24h: 2.35, changeYtd: 89.45 },
    { id: "tsmc", name: "TSMC", ticker: "TSM", marketCap: "$846.21B", price: "162.35", change24h: 1.23, changeYtd: 34.21 },
    { id: "samsung", name: "Samsung", ticker: "005930.KS", marketCap: "$456.72B", price: "68.42", change24h: -0.45, changeYtd: 15.32 },
    { id: "asml", name: "ASML", ticker: "ASML", marketCap: "$382.59B", price: "980.45", change24h: 1.87, changeYtd: 28.74 },
    { id: "intel", name: "Intel", ticker: "INTC", marketCap: "$181.34B", price: "43.61", change24h: -1.02, changeYtd: -3.21 },
    { id: "skhynix", name: "SK hynix", ticker: "000660.KS", marketCap: "$130.52B", price: "91.23", change24h: 2.15, changeYtd: 41.23 },
    { id: "qualcomm", name: "Qualcomm", ticker: "QCOM", marketCap: "$127.88B", price: "143.20", change24h: 0.78, changeYtd: 12.45 },
    { id: "micron", name: "Micron", ticker: "MU", marketCap: "$112.35B", price: "122.37", change24h: 1.65, changeYtd: 24.33 },
    { id: "ti", name: "Texas Instruments", ticker: "TXN", marketCap: "$96.21B", price: "171.23", change24h: 0.35, changeYtd: 8.21 },
    { id: "infineon", name: "Infineon", ticker: "IFX.DE", marketCap: "$69.15B", price: "34.21", change24h: -0.15, changeYtd: 6.12 },
  ],
  facilities: [
    { id: "f1", companyId: "tsmc", name: "Fab 18 (Hsinchu)", lat: 24.77, lng: 121.02, type: "fab", status: "operating" },
    { id: "f2", companyId: "tsmc", name: "Arizona Fab", lat: 33.45, lng: -112.07, type: "fab", status: "construction" },
    { id: "f3", companyId: "tsmc", name: "Kumamoto Fab", lat: 32.79, lng: 130.74, type: "fab", status: "operating" },
    { id: "f4", companyId: "samsung", name: "Pyeongtaek", lat: 36.99, lng: 127.11, type: "fab", status: "operating" },
    { id: "f5", companyId: "samsung", name: "Taylor, TX", lat: 30.57, lng: -97.41, type: "fab", status: "construction" },
    { id: "f6", companyId: "intel", name: "Ohio Fab", lat: 40.06, lng: -82.43, type: "fab", status: "planned" },
    { id: "f7", companyId: "intel", name: "Leixlip", lat: 53.36, lng: -6.49, type: "fab", status: "operating" },
    { id: "f8", companyId: "asml", name: "Veldhoven HQ", lat: 51.42, lng: 5.4, type: "hq", status: "operating" },
    { id: "f9", companyId: "skhynix", name: "Icheon", lat: 37.28, lng: 127.44, type: "fab", status: "operating" },
    { id: "f10", companyId: "micron", name: "Boise R&D", lat: 43.62, lng: -116.2, type: "rnd", status: "operating" },
    { id: "f11", companyId: "nvidia", name: "Santa Clara HQ", lat: 37.35, lng: -121.97, type: "hq", status: "operating" },
    { id: "f12", companyId: "infineon", name: "Dresden", lat: 51.05, lng: 13.74, type: "fab", status: "risk" },
    { id: "f13", companyId: "tsmc", name: "Dresden (ESMC)", lat: 51.06, lng: 13.72, type: "fab", status: "construction" },
    { id: "f14", companyId: "samsung", name: "Xi'an", lat: 34.34, lng: 108.94, type: "fab", status: "risk" },
  ],
  news: [
    { id: "n1", company: "NVIDIA", headline: "NVIDIA announces new AI chip architecture Blackwell", impact: "high", impactLabel: "Market Impact: High", ago: "2h ago" },
    { id: "n2", company: "TSMC", headline: "TSMC to build new fab in Germany with €10B investment", impact: "high", impactLabel: "Market Impact: High", ago: "5h ago" },
    { id: "n3", company: "USA", headline: "US tightens export restrictions on advanced chips to China", impact: "high", impactLabel: "Policy Impact: High", ago: "1d ago" },
    { id: "n4", company: "Lithium", headline: "Neon supply concerns resurface amid Eastern Europe tensions", impact: "medium", impactLabel: "Market Impact: Medium", ago: "1d ago" },
    { id: "n5", company: "Samsung", headline: "Samsung signs $16.5B foundry supply deal", impact: "medium", impactLabel: "Market Impact: Medium", ago: "1d ago" },
  ],
  radar: [
    { axis: "Geopolitical Risk", value: 82 },
    { axis: "Supplier Concentration", value: 74 },
    { axis: "Financial Stability", value: 35 },
    { axis: "Operational Risk", value: 58 },
    { axis: "Regulatory Risk", value: 66 },
    { axis: "ESG & Environmental Risk", value: 49 },
    { axis: "Raw Material Risk", value: 71 },
    { axis: "Logistics Risk", value: 55 },
  ],
  sankey: {
    nodes: [
      { name: "China" }, { name: "Japan" }, { name: "USA" }, { name: "Germany" }, { name: "Ukraine" },
      { name: "Silicon" }, { name: "Rare Earths" }, { name: "Photoresist" }, { name: "Gallium" }, { name: "Neon" },
      { name: "Taiwan" }, { name: "South Korea" }, { name: "USA " }, { name: "Japan " },
    ],
    links: [
      { source: 0, target: 5, value: 18 }, { source: 0, target: 6, value: 30 }, { source: 0, target: 8, value: 28 },
      { source: 1, target: 7, value: 26 }, { source: 2, target: 5, value: 14 }, { source: 3, target: 5, value: 12 },
      { source: 4, target: 9, value: 16 },
      { source: 5, target: 10, value: 20 }, { source: 5, target: 11, value: 14 }, { source: 5, target: 12, value: 12 },
      { source: 6, target: 10, value: 12 }, { source: 6, target: 13, value: 10 },
      { source: 7, target: 10, value: 12 }, { source: 7, target: 11, value: 10 },
      { source: 8, target: 10, value: 10 }, { source: 8, target: 12, value: 8 },
      { source: 9, target: 10, value: 10 }, { source: 9, target: 11, value: 8 },
    ],
  },
  financials: [
    { company: "NVIDIA", revenue: 235, profit: 120, rnd: 8.67, capex: 3.2 },
    { company: "TSMC", revenue: 90, profit: 36, rnd: 7.23, capex: 32 },
    { company: "Samsung", revenue: 200, profit: 27, rnd: 22.1, capex: 38 },
    { company: "ASML", revenue: 30, profit: 9, rnd: 4.5, capex: 2.1 },
    { company: "Intel", revenue: 53, profit: -0.3, rnd: 16, capex: 25 },
    { company: "SK hynix", revenue: 45, profit: 8, rnd: 3.6, capex: 12 },
    { company: "Qualcomm", revenue: 38, profit: 10, rnd: 8.8, capex: 1.5 },
    { company: "Micron", revenue: 25, profit: 5, rnd: 3.1, capex: 8 },
    { company: "TI", revenue: 17, profit: 6, rnd: 1.9, capex: 5 },
    { company: "Infineon", revenue: 16, profit: 3, rnd: 2.0, capex: 3 },
  ],
  deals: [
    { date: "May 20, 2024", parties: "TSMC ↔ Bosch", type: "Manufacturing Agreement", value: "$5.0B", description: "Long-term chip supply agreement" },
    { date: "May 18, 2024", parties: "Samsung ↔ Tesla", type: "Supply Agreement", value: "$16.5B", description: "AI chip supply for Tesla vehicles" },
    { date: "May 15, 2024", parties: "SK hynix ↔ NVIDIA", type: "Memory Supply", value: "$3.2B", description: "HBM memory supply agreement" },
    { date: "May 10, 2024", parties: "ASML ↔ Intel", type: "Equipment Supply", value: "$2.1B", description: "EUV lithography systems" },
    { date: "May 08, 2024", parties: "LG Energy ↔ GM", type: "Joint Venture", value: "$2.3B", description: "Battery cell manufacturing JV" },
  ],
  suppliers: [
    { name: "Applied Materials", category: "Equipment", spend: "$15.2B", risk: "medium" },
    { name: "ASML", category: "Equipment", spend: "$12.8B", risk: "medium" },
    { name: "Tokyo Electron", category: "Equipment", spend: "$9.7B", risk: "low" },
    { name: "Shin-Etsu Chemical", category: "Materials", spend: "$7.1B", risk: "low" },
    { name: "SUMCO", category: "Materials", spend: "$6.3B", risk: "medium" },
  ],
  research: [
    { company: "NVIDIA", rndExpense: "$8.67B", rndPctRevenue: "19.8%", patents: "1,867" },
    { company: "TSMC", rndExpense: "$7.23B", rndPctRevenue: "8.6%", patents: "2,615" },
    { company: "Samsung", rndExpense: "$22.1B", rndPctRevenue: "9.6%", patents: "7,123" },
    { company: "Intel", rndExpense: "$16.0B", rndPctRevenue: "32.1%", patents: "4,193" },
    { company: "Qualcomm", rndExpense: "$6.42B", rndPctRevenue: "24.3%", patents: "2,341" },
  ],
  companyMeta: {
    nvidia: { ceo: "Jensen Huang", hq: "Santa Clara, USA", employees: "29,600", founded: "1993", description: "Designs GPUs and accelerated-computing platforms powering AI, gaming, and datacenters.", healthScore: 94, exposure: "medium", segments: [{ name: "Data Center", share: 78 }, { name: "Gaming", share: 17 }, { name: "Pro Viz / Auto", share: 5 }] },
    tsmc: { ceo: "C.C. Wei", hq: "Hsinchu, Taiwan", employees: "73,000", founded: "1987", description: "World's largest dedicated semiconductor foundry, producing advanced logic for fabless designers.", healthScore: 88, exposure: "high", segments: [{ name: "HPC", share: 46 }, { name: "Smartphone", share: 33 }, { name: "IoT / Auto", share: 21 }] },
    samsung: { ceo: "Jong-Hee Han", hq: "Suwon, South Korea", employees: "267,000", founded: "1969", description: "Integrated memory + logic maker and the second-largest foundry.", healthScore: 79, exposure: "high", segments: [{ name: "Memory", share: 55 }, { name: "Foundry / LSI", share: 30 }, { name: "Other", share: 15 }] },
    asml: { ceo: "Christophe Fouquet", hq: "Veldhoven, Netherlands", employees: "42,000", founded: "1984", description: "Sole supplier of EUV lithography systems — a critical chokepoint in leading-edge chipmaking.", healthScore: 90, exposure: "medium", segments: [{ name: "EUV Systems", share: 48 }, { name: "DUV Systems", share: 34 }, { name: "Service", share: 18 }] },
    intel: { ceo: "Lip-Bu Tan", hq: "Santa Clara, USA", employees: "108,900", founded: "1968", description: "Integrated device manufacturer investing heavily in a foundry turnaround.", healthScore: 58, exposure: "high", segments: [{ name: "Client", share: 51 }, { name: "Data Center", share: 30 }, { name: "Foundry / Other", share: 19 }] },
    skhynix: { ceo: "Kwak Noh-Jung", hq: "Icheon, South Korea", employees: "31,000", founded: "1983", description: "Memory maker and leading supplier of HBM for AI accelerators.", healthScore: 82, exposure: "high", segments: [{ name: "DRAM / HBM", share: 71 }, { name: "NAND", share: 29 }] },
    qualcomm: { ceo: "Cristiano Amon", hq: "San Diego, USA", employees: "50,000", founded: "1985", description: "Fabless leader in mobile SoCs and wireless connectivity IP.", healthScore: 76, exposure: "medium", segments: [{ name: "Handsets", share: 64 }, { name: "IoT", share: 22 }, { name: "Automotive", share: 14 }] },
    micron: { ceo: "Sanjay Mehrotra", hq: "Boise, USA", employees: "48,000", founded: "1978", description: "US-based DRAM and NAND memory manufacturer.", healthScore: 74, exposure: "high", segments: [{ name: "DRAM", share: 73 }, { name: "NAND", share: 27 }] },
    ti: { ceo: "Haviv Ilan", hq: "Dallas, USA", employees: "34,000", founded: "1930", description: "Broad-line analog and embedded-processing supplier with in-house fabs.", healthScore: 80, exposure: "low", segments: [{ name: "Analog", share: 74 }, { name: "Embedded", share: 18 }, { name: "Other", share: 8 }] },
    infineon: { ceo: "Jochen Hanebeck", hq: "Neubiberg, Germany", employees: "58,000", founded: "1999", description: "Power semiconductors and automotive/industrial microcontrollers.", healthScore: 77, exposure: "medium", segments: [{ name: "Automotive", share: 48 }, { name: "Power & Sensor", share: 30 }, { name: "Connected / Secure", share: 22 }] },
  },
};

const ai: IndustryData = {
  kpis: [
    { label: "Companies Tracked", value: "10", icon: "Building2", accent: "#3b82f6" },
    { label: "Suppliers & Vendors Monitored", value: "1,884", icon: "Users", accent: "#a78bfa" },
    { label: "Facilities Worldwide", value: "612", icon: "Factory", accent: "#22d3ee" },
    { label: "Raw Materials Tracked", value: "1,204", icon: "Boxes", accent: "#f59e0b" },
    { label: "Countries Monitored", value: "84", icon: "Globe", accent: "#34d399" },
    { label: "Policy & Regulatory Updates", value: "91", icon: "Scale", accent: "#f472b6" },
    { label: "News Impacting Markets", value: "203", icon: "Newspaper", accent: "#60a5fa" },
  ],
  companies: [
    { id: "microsoft", name: "Microsoft", ticker: "MSFT", marketCap: "$3.11T", price: "418.32", change24h: 0.92, changeYtd: 22.14 },
    { id: "nvidia", name: "NVIDIA", ticker: "NVDA", marketCap: "$2.31T", price: "934.89", change24h: 2.35, changeYtd: 89.45 },
    { id: "alphabet", name: "Alphabet", ticker: "GOOGL", marketCap: "$2.10T", price: "168.22", change24h: 1.11, changeYtd: 30.02 },
    { id: "amazon", name: "Amazon", ticker: "AMZN", marketCap: "$1.92T", price: "184.70", change24h: 0.54, changeYtd: 20.31 },
    { id: "meta", name: "Meta", ticker: "META", marketCap: "$1.28T", price: "502.30", change24h: 1.42, changeYtd: 42.18 },
    { id: "amd", name: "AMD", ticker: "AMD", marketCap: "$262.4B", price: "162.51", change24h: 2.88, changeYtd: 12.03 },
    { id: "oracle", name: "Oracle", ticker: "ORCL", marketCap: "$342.1B", price: "124.10", change24h: 0.66, changeYtd: 18.44 },
    { id: "coreweave", name: "CoreWeave", ticker: "Private", marketCap: "$19.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "openai", name: "OpenAI", ticker: "Private", marketCap: "$80.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "anthropic", name: "Anthropic", ticker: "Private", marketCap: "$18.4B", price: "—", change24h: 0, changeYtd: 0 },
  ],
  facilities: [
    { id: "a1", companyId: "microsoft", name: "Azure US-East DC", lat: 37.43, lng: -78.65, type: "backend", status: "operating" },
    { id: "a2", companyId: "amazon", name: "AWS Oregon", lat: 45.87, lng: -119.69, type: "backend", status: "operating" },
    { id: "a3", companyId: "alphabet", name: "Google DC Finland", lat: 60.56, lng: 27.19, type: "backend", status: "operating" },
    { id: "a4", companyId: "meta", name: "Meta DC Ireland", lat: 53.35, lng: -6.26, type: "backend", status: "operating" },
    { id: "a5", companyId: "coreweave", name: "CoreWeave NJ", lat: 40.73, lng: -74.17, type: "backend", status: "construction" },
    { id: "a6", companyId: "microsoft", name: "Azure Middle East", lat: 24.47, lng: 54.37, type: "backend", status: "planned" },
    { id: "a7", companyId: "amd", name: "AMD Santa Clara", lat: 37.35, lng: -121.95, type: "hq", status: "operating" },
    { id: "a8", companyId: "oracle", name: "OCI Ashburn", lat: 39.04, lng: -77.49, type: "backend", status: "operating" },
    { id: "a9", companyId: "microsoft", name: "Azure Singapore", lat: 1.35, lng: 103.82, type: "backend", status: "risk" },
    { id: "a10", companyId: "alphabet", name: "Google DC Taiwan", lat: 23.5, lng: 120.4, type: "backend", status: "risk" },
  ],
  news: [
    { id: "an1", company: "OpenAI", headline: "OpenAI unveils next-gen model with expanded context", impact: "high", impactLabel: "Market Impact: High", ago: "3h ago" },
    { id: "an2", company: "Microsoft", headline: "Microsoft commits $80B to AI datacenter buildout", impact: "high", impactLabel: "Market Impact: High", ago: "6h ago" },
    { id: "an3", company: "USA", headline: "New AI compute export controls proposed", impact: "high", impactLabel: "Policy Impact: High", ago: "1d ago" },
    { id: "an4", company: "NVIDIA", headline: "HBM supply tightness expected through 2025", impact: "medium", impactLabel: "Market Impact: Medium", ago: "1d ago" },
    { id: "an5", company: "CoreWeave", headline: "CoreWeave secures $7.5B debt for GPU expansion", impact: "medium", impactLabel: "Market Impact: Medium", ago: "2d ago" },
  ],
  radar: [
    { axis: "Geopolitical Risk", value: 70 },
    { axis: "Supplier Concentration", value: 88 },
    { axis: "Financial Stability", value: 30 },
    { axis: "Operational Risk", value: 62 },
    { axis: "Regulatory Risk", value: 74 },
    { axis: "ESG & Environmental Risk", value: 68 },
    { axis: "Raw Material Risk", value: 55 },
    { axis: "Logistics Risk", value: 48 },
  ],
  sankey: {
    nodes: [
      { name: "Taiwan" }, { name: "South Korea" }, { name: "USA" }, { name: "Japan" },
      { name: "GPUs" }, { name: "HBM Memory" }, { name: "CoWoS Packaging" }, { name: "AI Servers" },
      { name: "USA " }, { name: "China" }, { name: "Europe" }, { name: "Middle East" },
    ],
    links: [
      { source: 0, target: 4, value: 26 }, { source: 0, target: 6, value: 18 }, { source: 1, target: 5, value: 20 },
      { source: 2, target: 4, value: 14 }, { source: 3, target: 5, value: 6 }, { source: 3, target: 6, value: 6 },
      { source: 4, target: 7, value: 26 }, { source: 4, target: 9, value: 6 }, { source: 5, target: 7, value: 20 },
      { source: 6, target: 7, value: 18 },
      { source: 7, target: 8, value: 34 }, { source: 7, target: 10, value: 14 }, { source: 7, target: 11, value: 12 },
    ],
  },
  financials: [
    { company: "Microsoft", revenue: 245, profit: 88, rnd: 29, capex: 55 },
    { company: "NVIDIA", revenue: 235, profit: 120, rnd: 8.67, capex: 3.2 },
    { company: "Alphabet", revenue: 328, profit: 74, rnd: 45, capex: 48 },
    { company: "Amazon", revenue: 620, profit: 37, rnd: 86, capex: 75 },
    { company: "Meta", revenue: 156, profit: 55, rnd: 38, capex: 37 },
    { company: "AMD", revenue: 25, profit: 4, rnd: 6.1, capex: 0.7 },
    { company: "Oracle", revenue: 53, profit: 10, rnd: 8.9, capex: 7 },
  ],
  deals: [
    { date: "May 22, 2024", parties: "Microsoft ↔ OpenAI", type: "Partnership", value: "$10.0B", description: "Multi-year Azure compute + investment" },
    { date: "May 19, 2024", parties: "Amazon ↔ Anthropic", type: "Investment", value: "$4.0B", description: "Strategic AI investment + Trainium" },
    { date: "May 14, 2024", parties: "CoreWeave ↔ NVIDIA", type: "Supply Agreement", value: "$3.5B", description: "GPU capacity commitment" },
    { date: "May 09, 2024", parties: "Oracle ↔ xAI", type: "Cloud Agreement", value: "$2.0B", description: "Grok training cluster" },
    { date: "May 05, 2024", parties: "Meta ↔ Scale AI", type: "Investment", value: "$1.5B", description: "Data labeling partnership" },
  ],
  suppliers: [
    { name: "NVIDIA", category: "Accelerators", spend: "$28.4B", risk: "high" },
    { name: "TSMC", category: "Foundry", spend: "$14.2B", risk: "medium" },
    { name: "SK hynix", category: "HBM Memory", spend: "$9.1B", risk: "medium" },
    { name: "Dell", category: "Systems", spend: "$6.7B", risk: "low" },
    { name: "Vertiv", category: "Cooling/Power", spend: "$4.3B", risk: "low" },
  ],
  research: [
    { company: "Alphabet", rndExpense: "$45.4B", rndPctRevenue: "13.8%", patents: "9,842" },
    { company: "Microsoft", rndExpense: "$29.5B", rndPctRevenue: "12.0%", patents: "8,912" },
    { company: "Meta", rndExpense: "$38.4B", rndPctRevenue: "24.6%", patents: "3,204" },
    { company: "NVIDIA", rndExpense: "$8.67B", rndPctRevenue: "19.8%", patents: "1,867" },
    { company: "AMD", rndExpense: "$6.1B", rndPctRevenue: "24.4%", patents: "2,410" },
  ],
};

const battery: IndustryData = {
  kpis: [
    { label: "Companies Tracked", value: "10", icon: "Building2", accent: "#3b82f6" },
    { label: "Suppliers & Vendors Monitored", value: "1,320", icon: "Users", accent: "#a78bfa" },
    { label: "Facilities Worldwide", value: "884", icon: "Factory", accent: "#22d3ee" },
    { label: "Raw Materials Tracked", value: "2,140", icon: "Boxes", accent: "#f59e0b" },
    { label: "Countries Monitored", value: "96", icon: "Globe", accent: "#34d399" },
    { label: "Policy & Regulatory Updates", value: "77", icon: "Scale", accent: "#f472b6" },
    { label: "News Impacting Markets", value: "118", icon: "Newspaper", accent: "#60a5fa" },
  ],
  companies: [
    { id: "catl", name: "CATL", ticker: "300750.SZ", marketCap: "$130.4B", price: "25.60", change24h: 1.02, changeYtd: 14.32 },
    { id: "byd", name: "BYD", ticker: "1211.HK", marketCap: "$92.1B", price: "31.20", change24h: -0.62, changeYtd: 9.41 },
    { id: "tesla", name: "Tesla", ticker: "TSLA", marketCap: "$798.2B", price: "251.10", change24h: 2.14, changeYtd: -3.22 },
    { id: "lges", name: "LG Energy", ticker: "373220.KS", marketCap: "$68.0B", price: "290.00", change24h: 0.51, changeYtd: 6.10 },
    { id: "panasonic", name: "Panasonic", ticker: "6752.T", marketCap: "$28.5B", price: "12.40", change24h: -0.31, changeYtd: 3.20 },
    { id: "samsungsdi", name: "Samsung SDI", ticker: "006400.KS", marketCap: "$22.0B", price: "230.00", change24h: 0.72, changeYtd: 5.90 },
    { id: "skon", name: "SK On", ticker: "Private", marketCap: "$20.0B", price: "—", change24h: 0, changeYtd: 0 },
    { id: "calb", name: "CALB", ticker: "3931.HK", marketCap: "$8.4B", price: "6.10", change24h: -1.02, changeYtd: -2.10 },
    { id: "eve", name: "EVE Energy", ticker: "300014.SZ", marketCap: "$11.2B", price: "5.80", change24h: 0.41, changeYtd: 4.30 },
    { id: "gotion", name: "Gotion", ticker: "002074.SZ", marketCap: "$6.1B", price: "3.20", change24h: -0.15, changeYtd: 1.10 },
  ],
  facilities: [
    { id: "b1", companyId: "catl", name: "Ningde Gigafactory", lat: 26.66, lng: 119.55, type: "fab", status: "operating" },
    { id: "b2", companyId: "catl", name: "Germany Plant", lat: 50.86, lng: 12.13, type: "fab", status: "operating" },
    { id: "b3", companyId: "byd", name: "Shenzhen HQ", lat: 22.65, lng: 114.05, type: "hq", status: "operating" },
    { id: "b4", companyId: "tesla", name: "Nevada Gigafactory", lat: 39.54, lng: -119.44, type: "fab", status: "operating" },
    { id: "b5", companyId: "tesla", name: "Berlin Gigafactory", lat: 52.4, lng: 13.79, type: "fab", status: "operating" },
    { id: "b6", companyId: "lges", name: "Ohio JV (Ultium)", lat: 41.16, lng: -80.58, type: "fab", status: "construction" },
    { id: "b7", companyId: "panasonic", name: "Kansas Plant", lat: 39.11, lng: -95.68, type: "fab", status: "construction" },
    { id: "b8", companyId: "catl", name: "Lithium Refinery (Yichun)", lat: 27.81, lng: 114.42, type: "refinery", status: "operating" },
    { id: "b9", companyId: "samsungsdi", name: "Cheonan", lat: 36.81, lng: 127.11, type: "fab", status: "operating" },
    { id: "b10", companyId: "catl", name: "DR Congo Sourcing", lat: -10.72, lng: 25.5, type: "refinery", status: "risk" },
  ],
  news: [
    { id: "bn1", company: "CATL", headline: "CATL unveils sodium-ion battery for mass production", impact: "high", impactLabel: "Market Impact: High", ago: "4h ago" },
    { id: "bn2", company: "Lithium", headline: "Lithium prices drop 15% amid supply glut concerns", impact: "medium", impactLabel: "Market Impact: Medium", ago: "8h ago" },
    { id: "bn3", company: "EU", headline: "EU Critical Raw Materials Act enters new phase", impact: "high", impactLabel: "Policy Impact: High", ago: "1d ago" },
    { id: "bn4", company: "DR Congo", headline: "Cobalt supply disruption risk rises in DRC", impact: "high", impactLabel: "Market Impact: High", ago: "1d ago" },
    { id: "bn5", company: "LG Energy", headline: "LG Energy ↔ GM expand Ultium JV capacity", impact: "medium", impactLabel: "Market Impact: Medium", ago: "2d ago" },
  ],
  radar: [
    { axis: "Geopolitical Risk", value: 78 },
    { axis: "Supplier Concentration", value: 84 },
    { axis: "Financial Stability", value: 45 },
    { axis: "Operational Risk", value: 60 },
    { axis: "Regulatory Risk", value: 62 },
    { axis: "ESG & Environmental Risk", value: 80 },
    { axis: "Raw Material Risk", value: 86 },
    { axis: "Logistics Risk", value: 58 },
  ],
  sankey: {
    nodes: [
      { name: "Australia" }, { name: "DR Congo" }, { name: "Chile" }, { name: "China" }, { name: "Indonesia" },
      { name: "Lithium" }, { name: "Cobalt" }, { name: "Nickel" }, { name: "Graphite" },
      { name: "China " }, { name: "South Korea" }, { name: "USA" }, { name: "Europe" },
    ],
    links: [
      { source: 0, target: 5, value: 24 }, { source: 2, target: 5, value: 16 }, { source: 1, target: 6, value: 22 },
      { source: 4, target: 7, value: 26 }, { source: 3, target: 8, value: 20 }, { source: 0, target: 7, value: 8 },
      { source: 5, target: 9, value: 20 }, { source: 5, target: 10, value: 10 }, { source: 5, target: 11, value: 8 },
      { source: 6, target: 9, value: 16 }, { source: 6, target: 10, value: 8 },
      { source: 7, target: 9, value: 16 }, { source: 7, target: 12, value: 8 },
      { source: 8, target: 9, value: 12 }, { source: 8, target: 11, value: 6 },
    ],
  },
  financials: [
    { company: "Tesla", revenue: 97, profit: 15, rnd: 4.0, capex: 9 },
    { company: "CATL", revenue: 56, profit: 6, rnd: 2.5, capex: 8 },
    { company: "BYD", revenue: 84, profit: 4.5, rnd: 3.9, capex: 11 },
    { company: "LG Energy", revenue: 24, profit: 1.5, rnd: 0.9, capex: 6 },
    { company: "Panasonic", revenue: 63, profit: 3, rnd: 2.1, capex: 4 },
    { company: "Samsung SDI", revenue: 18, profit: 1.2, rnd: 0.8, capex: 3 },
  ],
  deals: [
    { date: "May 21, 2024", parties: "LG Energy ↔ GM", type: "Joint Venture", value: "$2.3B", description: "Ultium cell manufacturing JV" },
    { date: "May 17, 2024", parties: "CATL ↔ Ford", type: "Licensing", value: "$3.5B", description: "LFP battery tech licensing" },
    { date: "May 12, 2024", parties: "Tesla ↔ Panasonic", type: "Supply Agreement", value: "$4.1B", description: "4680 cell supply" },
    { date: "May 07, 2024", parties: "BYD ↔ Toyota", type: "Partnership", value: "$1.8B", description: "EV platform co-development" },
    { date: "May 03, 2024", parties: "SK On ↔ Hyundai", type: "Joint Venture", value: "$2.0B", description: "US cell plant JV" },
  ],
  suppliers: [
    { name: "Ganfeng Lithium", category: "Lithium", spend: "$8.9B", risk: "high" },
    { name: "Glencore", category: "Cobalt/Nickel", spend: "$7.2B", risk: "high" },
    { name: "Albemarle", category: "Lithium", spend: "$5.4B", risk: "medium" },
    { name: "Umicore", category: "Cathode", spend: "$4.1B", risk: "medium" },
    { name: "POSCO Future M", category: "Anode/Cathode", spend: "$3.6B", risk: "low" },
  ],
  research: [
    { company: "CATL", rndExpense: "$2.5B", rndPctRevenue: "4.5%", patents: "6,120" },
    { company: "BYD", rndExpense: "$3.9B", rndPctRevenue: "4.6%", patents: "8,410" },
    { company: "Tesla", rndExpense: "$4.0B", rndPctRevenue: "4.1%", patents: "1,940" },
    { company: "LG Energy", rndExpense: "$0.9B", rndPctRevenue: "3.8%", patents: "2,780" },
    { company: "Samsung SDI", rndExpense: "$0.8B", rndPctRevenue: "4.4%", patents: "3,010" },
  ],
};

export const DATA: Record<Industry, IndustryData> = { semiconductor, ai, battery };

export function getIndustryData(industry: Industry): IndustryData {
  return DATA[industry];
}
